/**
 * Resolves a free-form trip location string (e.g. "Roma, Italia",
 * "Parigi, Francia", "Tokyo, Japan", "USA") into the corresponding ISO
 * 3166-1 alpha-2 country code and a flag emoji.
 *
 * The lookup is purely lexical: we don't call a geocoder here so the
 * function is synchronous, cacheable and safe to call during render.
 *
 * Strategy:
 *   1. Split the input on commas and try each segment from the last (most
 *      likely the country) to the first.
 *   2. Normalize each candidate (lowercase, strip diacritics) and look it
 *      up in a dictionary that maps Italian / English / native names to
 *      ISO codes.
 *   3. Convert the ISO code to a flag emoji using regional indicator
 *      symbols.
 */

/** Country dictionary — covers EU + common travel destinations.
 *
 *  Keys (after normalization) include Italian + English + a few native
 *  spellings. Add more entries here freely; the lookup is forgiving.
 */
const COUNTRY_BY_NAME: Record<string, string> = {
  // ── Europe ────────────────────────────────────────────────────────────
  italia: "IT",
  italy: "IT",
  austria: "AT",
  belgio: "BE",
  belgium: "BE",
  bulgaria: "BG",
  cipro: "CY",
  cyprus: "CY",
  croazia: "HR",
  croatia: "HR",
  danimarca: "DK",
  denmark: "DK",
  estonia: "EE",
  finlandia: "FI",
  finland: "FI",
  francia: "FR",
  france: "FR",
  germania: "DE",
  germany: "DE",
  deutschland: "DE",
  grecia: "GR",
  greece: "GR",
  irlanda: "IE",
  ireland: "IE",
  lettonia: "LV",
  latvia: "LV",
  lituania: "LT",
  lithuania: "LT",
  lussemburgo: "LU",
  luxembourg: "LU",
  malta: "MT",
  "paesi bassi": "NL",
  olanda: "NL",
  netherlands: "NL",
  holland: "NL",
  polonia: "PL",
  poland: "PL",
  portogallo: "PT",
  portugal: "PT",
  "repubblica ceca": "CZ",
  cechia: "CZ",
  czechia: "CZ",
  "czech republic": "CZ",
  romania: "RO",
  slovacchia: "SK",
  slovakia: "SK",
  slovenia: "SI",
  spagna: "ES",
  spain: "ES",
  espana: "ES",
  svezia: "SE",
  sweden: "SE",
  ungheria: "HU",
  hungary: "HU",
  norvegia: "NO",
  norway: "NO",
  islanda: "IS",
  iceland: "IS",
  svizzera: "CH",
  switzerland: "CH",
  "regno unito": "GB",
  inghilterra: "GB",
  uk: "GB",
  "united kingdom": "GB",
  britain: "GB",
  scozia: "GB",
  scotland: "GB",
  galles: "GB",
  wales: "GB",
  albania: "AL",
  serbia: "RS",
  bosnia: "BA",
  "bosnia ed erzegovina": "BA",
  "bosnia and herzegovina": "BA",
  montenegro: "ME",
  macedonia: "MK",
  "macedonia del nord": "MK",
  "north macedonia": "MK",
  kosovo: "XK",
  moldova: "MD",
  moldavia: "MD",
  ucraina: "UA",
  ukraine: "UA",
  bielorussia: "BY",
  belarus: "BY",
  russia: "RU",
  turchia: "TR",
  turkey: "TR",
  vaticano: "VA",
  vatican: "VA",
  monaco: "MC",
  andorra: "AD",
  "san marino": "SM",
  liechtenstein: "LI",
  "isole faroe": "FO",
  "faroe islands": "FO",

  // ── Americas ──────────────────────────────────────────────────────────
  "stati uniti": "US",
  "stati uniti d'america": "US",
  usa: "US",
  "u.s.a.": "US",
  "united states": "US",
  "united states of america": "US",
  america: "US",
  canada: "CA",
  messico: "MX",
  mexico: "MX",
  cuba: "CU",
  "repubblica dominicana": "DO",
  "dominican republic": "DO",
  giamaica: "JM",
  jamaica: "JM",
  bahamas: "BS",
  haiti: "HT",
  "porto rico": "PR",
  "puerto rico": "PR",
  "costa rica": "CR",
  panama: "PA",
  guatemala: "GT",
  honduras: "HN",
  "el salvador": "SV",
  nicaragua: "NI",
  brasile: "BR",
  brazil: "BR",
  argentina: "AR",
  cile: "CL",
  chile: "CL",
  peru: "PE",
  perù: "PE",
  colombia: "CO",
  venezuela: "VE",
  uruguay: "UY",
  paraguay: "PY",
  bolivia: "BO",
  ecuador: "EC",

  // ── Asia ──────────────────────────────────────────────────────────────
  giappone: "JP",
  japan: "JP",
  cina: "CN",
  china: "CN",
  "hong kong": "HK",
  taiwan: "TW",
  "corea del sud": "KR",
  "south korea": "KR",
  corea: "KR",
  korea: "KR",
  "corea del nord": "KP",
  "north korea": "KP",
  thailandia: "TH",
  thailand: "TH",
  vietnam: "VN",
  cambogia: "KH",
  cambodia: "KH",
  laos: "LA",
  malesia: "MY",
  malaysia: "MY",
  singapore: "SG",
  indonesia: "ID",
  filippine: "PH",
  philippines: "PH",
  india: "IN",
  pakistan: "PK",
  bangladesh: "BD",
  "sri lanka": "LK",
  nepal: "NP",
  "emirati arabi uniti": "AE",
  emirati: "AE",
  uae: "AE",
  "united arab emirates": "AE",
  dubai: "AE",
  qatar: "QA",
  oman: "OM",
  "arabia saudita": "SA",
  "saudi arabia": "SA",
  bahrain: "BH",
  kuwait: "KW",
  giordania: "JO",
  jordan: "JO",
  libano: "LB",
  lebanon: "LB",
  israele: "IL",
  israel: "IL",
  palestina: "PS",
  palestine: "PS",
  iran: "IR",
  iraq: "IQ",
  siria: "SY",
  syria: "SY",
  georgia: "GE",
  armenia: "AM",
  azerbaijan: "AZ",
  azerbaigian: "AZ",
  kazakistan: "KZ",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
  mongolia: "MN",

  // ── Africa ────────────────────────────────────────────────────────────
  egitto: "EG",
  egypt: "EG",
  marocco: "MA",
  morocco: "MA",
  tunisia: "TN",
  algeria: "DZ",
  libia: "LY",
  libya: "LY",
  sudafrica: "ZA",
  "sud africa": "ZA",
  "south africa": "ZA",
  kenya: "KE",
  tanzania: "TZ",
  uganda: "UG",
  etiopia: "ET",
  ethiopia: "ET",
  ghana: "GH",
  nigeria: "NG",
  senegal: "SN",
  "capo verde": "CV",
  "cape verde": "CV",
  madagascar: "MG",
  mauritius: "MU",
  seychelles: "SC",
  zimbabwe: "ZW",
  namibia: "NA",
  botswana: "BW",
  mozambico: "MZ",
  mozambique: "MZ",

  // ── Oceania ───────────────────────────────────────────────────────────
  australia: "AU",
  "nuova zelanda": "NZ",
  "new zealand": "NZ",
  figi: "FJ",
  fiji: "FJ",

  // ── Major cities → country (fallback when location lacks the country)
  // Italy
  roma: "IT",
  rome: "IT",
  milano: "IT",
  milan: "IT",
  napoli: "IT",
  naples: "IT",
  torino: "IT",
  turin: "IT",
  firenze: "IT",
  florence: "IT",
  venezia: "IT",
  venice: "IT",
  bologna: "IT",
  palermo: "IT",
  catania: "IT",
  genova: "IT",
  genoa: "IT",
  bari: "IT",
  verona: "IT",
  padova: "IT",
  trieste: "IT",
  cagliari: "IT",
  pisa: "IT",
  siena: "IT",
  lecce: "IT",
  rimini: "IT",
  parma: "IT",
  matera: "IT",
  perugia: "IT",
  amalfi: "IT",
  positano: "IT",
  sorrento: "IT",
  capri: "IT",
  taormina: "IT",
  // France
  parigi: "FR",
  paris: "FR",
  lione: "FR",
  lyon: "FR",
  marsiglia: "FR",
  marseille: "FR",
  nizza: "FR",
  nice: "FR",
  bordeaux: "FR",
  tolosa: "FR",
  toulouse: "FR",
  strasburgo: "FR",
  strasbourg: "FR",
  cannes: "FR",
  // Spain
  madrid: "ES",
  barcellona: "ES",
  barcelona: "ES",
  siviglia: "ES",
  seville: "ES",
  sevilla: "ES",
  valencia: "ES",
  valenza: "ES",
  granada: "ES",
  malaga: "ES",
  bilbao: "ES",
  ibiza: "ES",
  maiorca: "ES",
  mallorca: "ES",
  tenerife: "ES",
  // UK
  londra: "GB",
  london: "GB",
  manchester: "GB",
  liverpool: "GB",
  edimburgo: "GB",
  edinburgh: "GB",
  glasgow: "GB",
  dublino: "IE",
  dublin: "IE",
  // Germany — "monaco" alone stays the principality (MC) defined above;
  // "Monaco di Baviera" / "Munich" disambiguates to Germany.
  berlino: "DE",
  berlin: "DE",
  munich: "DE",
  "monaco di baviera": "DE",
  amburgo: "DE",
  hamburg: "DE",
  francoforte: "DE",
  frankfurt: "DE",
  colonia: "DE",
  cologne: "DE",
  // Netherlands / Belgium
  amsterdam: "NL",
  rotterdam: "NL",
  utrecht: "NL",
  bruxelles: "BE",
  brussels: "BE",
  bruges: "BE",
  brugge: "BE",
  anversa: "BE",
  antwerp: "BE",
  // Portugal
  lisbona: "PT",
  lisbon: "PT",
  porto: "PT",
  madeira: "PT",
  // Switzerland
  zurigo: "CH",
  zurich: "CH",
  ginevra: "CH",
  geneva: "CH",
  berna: "CH",
  bern: "CH",
  lucerna: "CH",
  lucerne: "CH",
  // Austria / Hungary / Czechia
  vienna: "AT",
  wien: "AT",
  salisburgo: "AT",
  salzburg: "AT",
  innsbruck: "AT",
  budapest: "HU",
  praga: "CZ",
  prague: "CZ",
  // Nordics
  copenaghen: "DK",
  copenhagen: "DK",
  stoccolma: "SE",
  stockholm: "SE",
  oslo: "NO",
  helsinki: "FI",
  reykjavik: "IS",
  // Greece
  atene: "GR",
  athens: "GR",
  santorini: "GR",
  mykonos: "GR",
  creta: "GR",
  crete: "GR",
  corfu: "GR",
  rodi: "GR",
  rhodes: "GR",
  // Croatia
  zagabria: "HR",
  zagreb: "HR",
  dubrovnik: "HR",
  spalato: "HR",
  split: "HR",
  // Eastern Europe
  varsavia: "PL",
  warsaw: "PL",
  cracovia: "PL",
  krakow: "PL",
  bucarest: "RO",
  bucharest: "RO",
  sofia: "BG",
  belgrado: "RS",
  belgrade: "RS",
  istanbul: "TR",
  ankara: "TR",
  // North America
  "new york": "US",
  newyork: "US",
  nyc: "US",
  "los angeles": "US",
  la: "US",
  "san francisco": "US",
  chicago: "US",
  miami: "US",
  "las vegas": "US",
  "washington dc": "US",
  washington: "US",
  boston: "US",
  seattle: "US",
  orlando: "US",
  "new orleans": "US",
  hawaii: "US",
  honolulu: "US",
  toronto: "CA",
  montreal: "CA",
  vancouver: "CA",
  "città del messico": "MX",
  "mexico city": "MX",
  cancun: "MX",
  // South America
  "rio de janeiro": "BR",
  rio: "BR",
  "san paolo": "BR",
  "são paulo": "BR",
  "sao paulo": "BR",
  "buenos aires": "AR",
  "santiago del cile": "CL",
  santiago: "CL",
  cusco: "PE",
  lima: "PE",
  // Asia
  tokyo: "JP",
  kyoto: "JP",
  osaka: "JP",
  yokohama: "JP",
  pechino: "CN",
  beijing: "CN",
  shanghai: "CN",
  hongkong: "HK",
  taipei: "TW",
  seoul: "KR",
  busan: "KR",
  bangkok: "TH",
  phuket: "TH",
  "chiang mai": "TH",
  hanoi: "VN",
  saigon: "VN",
  "ho chi minh": "VN",
  bali: "ID",
  jakarta: "ID",
  "kuala lumpur": "MY",
  manila: "PH",
  delhi: "IN",
  "new delhi": "IN",
  mumbai: "IN",
  bombay: "IN",
  goa: "IN",
  jaipur: "IN",
  bangalore: "IN",
  kerala: "IN",
  agra: "IN",
  kathmandu: "NP",
  colombo: "LK",
  // Middle East
  "abu dhabi": "AE",
  "tel aviv": "IL",
  gerusalemme: "IL",
  jerusalem: "IL",
  amman: "JO",
  petra: "JO",
  doha: "QA",
  // Africa
  cairo: "EG",
  "il cairo": "EG",
  marrakech: "MA",
  marrakesh: "MA",
  casablanca: "MA",
  fes: "MA",
  fez: "MA",
  tangeri: "MA",
  tangier: "MA",
  cartagine: "TN",
  tunisi: "TN",
  tunis: "TN",
  "cape town": "ZA",
  "città del capo": "ZA",
  johannesburg: "ZA",
  nairobi: "KE",
  zanzibar: "TZ",
  // Oceania
  sydney: "AU",
  melbourne: "AU",
  brisbane: "AU",
  perth: "AU",
  auckland: "NZ",
  wellington: "NZ",
  queenstown: "NZ",

  // ── Common 2-letter / ISO short forms ────────────────────────────────
  it: "IT",
  fr: "FR",
  de: "DE",
  es: "ES",
  pt: "PT",
  nl: "NL",
  be: "BE",
  ch: "CH",
  at: "AT",
  pl: "PL",
  cz: "CZ",
  ie: "IE",
  gr: "GR",
  hr: "HR",
  hu: "HU",
  ro: "RO",
  bg: "BG",
  fi: "FI",
  se: "SE",
  no: "NO",
  dk: "DK",
  is: "IS",
  gb: "GB",
  us: "US",
  ca: "CA",
  mx: "MX",
  br: "BR",
  ar: "AR",
  jp: "JP",
  cn: "CN",
  kr: "KR",
  in: "IN",
  th: "TH",
  vn: "VN",
  id: "ID",
  ph: "PH",
  sg: "SG",
  au: "AU",
  nz: "NZ",
  ae: "AE",
  tr: "TR",
  eg: "EG",
  ma: "MA",
  za: "ZA",
};

/** Strip diacritics + lowercase + collapse whitespace. */
function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[.]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Converts an ISO 3166-1 alpha-2 country code to its flag emoji. */
export function flagEmojiFromCode(code: string): string {
  const cc = code.trim().toUpperCase();
  if (cc.length !== 2) return "";
  // Kosovo (XK) has no official Unicode flag — fall back to a generic
  // black flag so the UI doesn't show a broken glyph.
  if (cc === "XK") return "🏴";
  const A = 0x1f1e6;
  const codePointA = "A".charCodeAt(0);
  const first = A + (cc.charCodeAt(0) - codePointA);
  const second = A + (cc.charCodeAt(1) - codePointA);
  return String.fromCodePoint(first, second);
}

export interface CountryInfo {
  code: string;
  flag: string;
}

/**
 * Returns the country code + flag emoji for a free-form location string,
 * or `null` when the country couldn't be determined.
 */
export function getCountryFromLocation(location: string): CountryInfo | null {
  if (!location) return null;

  // Try each comma-separated segment, last to first (the country is most
  // commonly the rightmost segment, e.g. "Roma, Italia").
  const segments = location
    .split(",")
    .map((s) => normalize(s))
    .filter(Boolean);

  for (let i = segments.length - 1; i >= 0; i--) {
    const code = COUNTRY_BY_NAME[segments[i]];
    if (code) return { code, flag: flagEmojiFromCode(code) };
  }

  // Last resort: scan the full string for any known country name as a
  // substring (catches inputs without commas, e.g. "Trip to Japan").
  const whole = normalize(location);
  for (const [name, code] of Object.entries(COUNTRY_BY_NAME)) {
    // Skip 2-letter codes here — they're too short for substring matches.
    if (name.length <= 2) continue;
    if (whole.includes(name)) return { code, flag: flagEmojiFromCode(code) };
  }

  return null;
}

/** Shortcut returning just the emoji (or "" when unknown). */
export function getFlagEmoji(location: string): string {
  return getCountryFromLocation(location)?.flag ?? "";
}
